name: GitHub Actions Demo

on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le repository
        uses: actions/checkout@v4

      - name: Executer Python
        run: python3 job.py

      - name: Creer un fichier
        run: echo "Bonjour depuis GitHub Actions" > resultat.txt

      - name: Upload de l artefact
        uses: actions/upload-artifact@v4
        with:
          name: resultat-pipeline
          path: resultat.txt